class UserError(Exception):
    pass


class UserWarning(Exception):
    pass

